function [BW,maskedImage] = segmentImage(RGB)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the imageSegmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 21-Jul-2021
%----------------------------------------------------


% Convert RGB image into L*a*b* color space.
X = rgb2lab(RGB);

% Graph cut
foregroundInd = [426545 426552 426558 427565 429635 430633 430661 432675 433699 434761 439837 441883 448077 449045 460302 466444 468561 475658 478728 487944 494163 505350 505427 517635 518739 530003 530945 543230 546302 546387 555513 556537 558585 558675 560633 561657 562686 564729 566867 567803 572923 575997 575998 577107 581119 583251 586241 587265 589314 589393 591361 592386 594435 594512 600580 600581 600654 604748 605704 609800 609864 613898 616972 617029 619023 622097 622147 626196 627262 628246 631319 632379 634393 634426 637496 638493 639541 640544 640563 642595 642599 642601 642604 642608 ];
backgroundInd = [6638 7662 9710 11276 11279 11281 11282 11283 11284 11285 11758 14833 15857 17905 18929 19953 20466 20468 20469 21490 22514 22517 23538 23541 24562 25586 501746 502770 517139 518163 520210 520211 521234 522258 523282 524306 526354 527378 1017876 1017878 1019927 1020951 1022999 1023000 1025048 1026072 1028120 1029143 1031145 1031190 1033228 1033236 1034255 1034258 1035276 1035462 1036300 1036302 1036303 1041024 ];
L = superpixels(X,5343,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = lazysnapping(scaledX,L,foregroundInd,backgroundInd);

% Erode mask with rectangle
dimensions = [12 11];
se = strel('rectangle', dimensions);
BW = imerode(BW, se);

% Erode mask with rectangle
dimensions = [12 12];
se = strel('rectangle', dimensions);
BW = imerode(BW, se);

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

function out = prepLab(in)

% Convert L*a*b* image to range [0,1]
out = in;
out(:,:,1) = in(:,:,1) / 100;  % L range is [0 100].
out(:,:,2) = (in(:,:,2) + 86.1827) / 184.4170;  % a* range is [-86.1827,98.2343].
out(:,:,3) = (in(:,:,3) + 107.8602) / 202.3382;  % b* range is [-107.8602,94.4780].

end
